# Generated by Django 6.0.2 on 2026-02-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(help_text='Gene symbol (e.g., TP53)', max_length=100)),
                ('protein_name', models.CharField(blank=True, help_text='Full protein name', max_length=200)),
                ('uniprot_id', models.CharField(help_text='UniProt accession ID', max_length=50, unique=True)),
                ('ensembl_id', models.CharField(blank=True, help_text='Ensembl gene ID', max_length=100)),
                ('entrez_id', models.CharField(blank=True, help_text='Entrez/NCBI gene ID', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Protein function description')),
                ('sequence', models.TextField(blank=True, help_text='Amino acid sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protein',
                'verbose_name_plural': 'Proteins',
                'ordering': ['gene_name'],
            },
        ),
    ]
