# Generated by Django 6.0.2 on 2026-03-02 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Interaction confidence score (0-1)')),
                ('interaction_type', models.CharField(choices=[('physical', 'Physical'), ('genetic', 'Genetic'), ('regulatory', 'Regulatory'), ('predicted', 'Predicted')], default='physical', max_length=50)),
                ('dataset', models.CharField(help_text='Source dataset (e.g., STRING, BioGRID)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='proteins.protein')),
                ('protein_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='proteins.protein')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-score'],
                'unique_together': {('protein_a', 'protein_b', 'dataset')},
            },
        ),
    ]
